### PR TITLE
Discover broken links when building absolute links

### LINKED ISSUE #185: Discover broken links when building absolute links to documentation sources
**What happened**:
During Docforge replication of documentation nodes, there are cases where nodes could have references to documentation files (markdowns) that are outside of the scope of the particular build. Such references are transformed to absolute links (depending on the ResourceHandler responsible for the source node) or they are already such links. Sometimes those links are broken and we can add a check if they do actually exist in order to inform the user it might be broken.

**What you expected to happen**:
To be notified that an absolute link inside the replicated documentation points to a nonexisting source.

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**What this PR does / why we need it**:
Discover broken links when building absolute links

**Which issue(s) this PR fixes**:
Closes #185 
**Special notes for your reviewer**:
@swilen-iwanow 

**Release note**:

```noteworthy user
None
```

### CODE REVIEW

File: pkg/reactor/content_processor.go [hunk 1]
```diff
@@ -233,6 +233,10 @@ func (c *nodeContentProcessor) resolveLink(ctx context.Context, document *proces
 			return link, nil, err
 		}
 		link.AbsLink = &absLink
+
+		if _, err := handler.Read(ctx, absLink); err != nil {
+			klog.Warningf("absolute link %s not found: %s\n", absLink, err.Error())
```
Comment (swilen-iwanow) [inline pkg/reactor/content_processor.go:238]:
```suggestion
			klog.Warningf("failed to read absolute link %s: %v\n", absLink, err)
```

**Review by swilen-iwanow — CHANGES_REQUESTED** [review]
there are failing tests

**Comment by Kristian-ZH** [comment]
> there are failing tests

should be fine now

**Review by swilen-iwanow — APPROVED** [review]
