### PR TITLE
fix link removal

### LINKED ISSUE #158: Removing multiple completely yields runtime error
**What happened**:
Removing multiple links completely with a rewrite rule fails with runtime error. 

```
panic: runtime error: slice bounds out of range [:104] with capacity 64

goroutine 54 [running]:
github.com/gardener/docforge/pkg/markdown/parser.(*link).GetDestination(0xc0004180c0, 0xc0004101b7, 0x1, 0x9)
        /home/i024136/dev/docforge/pkg/markdown/parser/links.go:115 +0x8b
github.com/gardener/docforge/pkg/markdown.UpdateMarkdownLinks.func1(0xc1b180, 0xc0004180c0)
        /home/i024136/dev/docforge/pkg/markdown/links.go:79 +0xbd
github.com/gardener/docforge/pkg/markdown/parser.(*document).ListLinks(0xc000400060, 0xc00040c030)
        /home/i024136/dev/docforge/pkg/markdown/parser/document.go:15 +0x82
github.com/gardener/docforge/pkg/markdown.UpdateMarkdownLinks(0xc00040a000, 0xa9, 0x2a9, 0xc000418000, 0x0, 0xc00040a000, 0xa9, 0x2a9, 0x41)
        /home/i024136/dev/docforge/pkg/markdown/links.go:67 +0xc4
github.com/gardener/docforge/pkg/reactor.(*nodeContentProcessor).reconcileMDLinks(0xc0000bf380, 0xc15700, 0xc0000cb640, 0xc0001be3f0, 0xc00040a000, 0xa9, 0x2a9, 0xc0000a8150, 0x24, 0x0, ...)
        /home/i024136/dev/docforge/pkg/reactor/content_processor.go:104 +0xe9
github.com/gardener/docforge/pkg/reactor.(*nodeContentProcessor).ReconcileLinks(0xc0000bf380, 0xc15700, 0xc0000cb640, 0xc0001be3f0, 0xc0000a8150, 0x24, 0xc00040a000, 0xa9, 0x2a9, 0x0, ...)
        /home/i024136/dev/docforge/pkg/reactor/content_processor.go:87 +0x1cd
github.com/gardener/docforge/pkg/reactor.(*DocumentWorker).Work(0xc0001771f0, 0xc15700, 0xc0000cb640, 0xa23ce0, 0xc0000bc348, 0xc15940, 0xc0001731a0, 0x2)
        /home/i024136/dev/docforge/pkg/reactor/document_worker.go:142 +0x8ee
github.com/gardener/docforge/pkg/jobs.(*Job).startWorkers.func1(0xc00017d220, 0xc000304000, 0xc15700, 0xc0000cb640, 0x4, 0xc15940, 0xc0001731a0, 0xc000302000)
        /home/i024136/dev/docforge/pkg/jobs/jobs.go:248 +0x302
created by github.com/gardener/docforge/pkg/jobs.(*Job).startWorkers
        /home/i024136/dev/docforge/pkg/jobs/jobs.go:232 +0x115
```
**What you expected to happen**:
Links to be removed

**How to reproduce it (as minimally and precisely as possible)**:
- manifest:
```
structure:
- source: /home/user/test/links.md
links:
  rewrites:
    (pulls|pull|issues|issue|wiki): ~
```
- markdown ( /home/user/test/links.md) with multiple links that match rewrite rule that removes them:
```
[a](https://github.com/gardener/documentation/wiki/Architecture)
[b](https://github.com/gardener/gardener/issues/356)
[c](https://github.com/gardener/gardener/pull/2309)
```

**How to categorize this issue?**
/kind bug
/priority critical

### PR DESCRIPTION
**Pull request by g-pavlov**
**What this PR does / why we need it**:
Fixes positions offset during link removal. 
Fixes links slice removals on the fly.
Propagates update callback errors.

**Which issue(s) this PR fixes**:
Fixes #158 

**Release note**:

```noteworthy user
Fixes a runtime error when multiple links match a rewrite rule to be removed completely from a document.
```

### CODE REVIEW

File: pkg/markdown/parser/links.go [hunk 1]
```diff
@@ -142,30 +142,24 @@ func (l *link) Remove(leaveText bool) {
...
-		if l.document.links[i] == l {
-			removedElementIndex = i
-			needsOffset = true
+		if _l, ok = l.document.links[i].(*link); !ok {
 			continue
 		}
-		if needsOffset {
+		// links positioned after the removed one get offset
+		if l.end < _l.start {
 			offsetLinkByteRanges(l.document.links[i].(*link), offset)
```
Comment (swilen-iwanow) [inline pkg/markdown/parser/links.go:160]:
```suggestion
			offsetLinkByteRanges(_l, offset)
```

File: pkg/markdown/links.go [hunk 2]
```diff
@@ -77,17 +77,20 @@ func UpdateMarkdownLinks(documentBlob []byte, callback UpdateMarkdownLink) ([]by
...
+		return updateLink(l, destination, text, title)
 	})
+	if err != nil {
+		return nil, err
+	}
 	return document.Bytes(), nil
 }
 
-func updateLink(link parser.Link, destination, text, title []byte) {
+func updateLink(link parser.Link, destination, text, title []byte) (parser.Link, error) {
```
Comment (swilen-iwanow) [inline pkg/markdown/links.go:90]: this function never returns an error. was this intended

File: pkg/markdown/parser/document.go [hunk 3]
```diff
@@ -9,12 +9,27 @@ type document struct {
 	links []Link
 }
 
-func (d *document) ListLinks(cb UpdateMarkdownLinkListed) {
+func (d *document) ListLinks(cb UpdateMarkdownLinkListed) error {
```
Comment (swilen-iwanow) [inline pkg/markdown/parser/document.go:12]: I think ListLinks is not a suitable name anymore as it is updating the list. We should somehow suggest that if the callback returns nil for the link it will be removed from the list. What do you think

Comment (g-pavlov) [reply pkg/markdown/parser/document.go:12]: No, it still has the dedicated purpose to iterate links (maybe list should change to something more in the lines of iterate?). Note that it is `UpdateMarkdownLinks` (hence the name) that does changes. If you check its implementation you will notice that `UpdateMarkdownLinks` uses `ListLinks` to iterate on links and delegate link processing to a callback as a closure.

**Review by swilen-iwanow — APPROVED** [review]
