### PR TITLE
Do not panic when all git commits are internal

### LINKED ISSUE #114: Using docforge with `--github-info-destination` flag fails when all commits for a file are internal
**What happened**:
Using docforge with `--github-info-destination` flag fails with nil pointer reference panic when all commits for a file are internal.

**What you expected to happen**:
Ignore the file and proceed without panic.

**How to categorize this issue?**
/kind bug
/priority critical

### PR DESCRIPTION
**Pull request by g-pavlov**
**What this PR does / why we need it**:
Bugfix

**Which issue(s) this PR fixes**:
Fixes #114 

**Release note**:
```improvement user
Using docforge with `--github-info-destination` flag failed with nil pointer reference panic when all commits for a file referenced by a node source in the structure were internal. This is fixed now.
```

### CODE REVIEW

File: pkg/resourcehandlers/github/gitinfo.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ func transform(commits []*github.RepositoryCommit) *git.GitInfo {
 			nonInternalCommits = append(nonInternalCommits, commit)
 		}
 	}
-	if len(commits) == 0 {
+	if len(nonInternalCommits) == 0 {
```
Comment (swilen-iwanow) [inline pkg/resourcehandlers/github/gitinfo.go:27]: It would be good if we check for both lengths of commits and nonInternalCommits

**Review by swilen-iwanow — APPROVED** [review]

File: pkg/resourcehandlers/github/gitinfo.go (hunk 1 above)
Comment (g-pavlov) [reply pkg/resourcehandlers/github/gitinfo.go:30]: done =>early exit
