### PR TITLE
Common html link parser

### LINKED ISSUE #101: Failed to parse a link that contains src= with --hugo flag enabled
**What happened**:
Failed to parse a link that contains `src=`. Same as the issue fixed with #82 but applies when dockforge is run with `--hugo` flag
```
W1109 18:38:04.663167  814998 processor.go:77] Invalid link:gardener.cloud.community%40gmail.com), or paste this [iCal url](https://calendar.google.com/calendar/ical/gardener.cloud.community%40gmail.com/public/basic.ics) into any iCal client.

If you have a topic you'
```
**What you expected to happen**:
HTML links should be parsed correctly

**How to reproduce it (as minimally and precisely as possible)**:
Use https://raw.githubusercontent.com/gardener/documentation/master/CONTRIBUTING.md or use a document with similiar content:
```
[test](https://a.b/c?src=x)
```
**How to categorize this issue?**
/kind bug
/priority critical

### PR DESCRIPTION
**Pull request by g-pavlov**
**What this PR does / why we need it**:
The logic for parsing HTML links for rewriting is duplicated in hugo processor and reactor.nodeContentProcessor. This duplication proved hard to maintain. it can an should be generalized similar to handling MD links and that's what this PR does. 

**Which issue(s) this PR fixes**:
Fixes #101 

**Special notes for your reviewer**:
Golang features a builtin HTML parser that does the job of finding links properly. However when it comes back to writing back its renderer does that on best effort and can introduce side-effects as we had with the markdown parsers. On the other hand the regex based solution is missing context on a match (can't tell tag, title, text) and updates are feasible only on the destination component, which we do.    
Perhaps a hybrid solution with traceback for the tag with parser that can give us more context or something in the lines of what we did with the markdown parsers for links is the way to go here. But that will be subject of another PR.

**Release note**:
```improvement user
Fixes an issue with failing parse of HTML links when dockforge is run with `--hugo` flag
```

### CODE REVIEW

File: pkg/hugo/processor.go [hunk 1]
```diff
@@ -12,17 +12,14 @@ import (
...
 	mdutil "github.com/gardener/docforge/pkg/markdown"
 )
 
 var (
-	htmlLinksRegexList = []*regexp.Regexp{
-		regexp.MustCompile(`href=["\']?([^"\'>]+)["\']?`),
-		regexp.MustCompile(`src=["\']?([^"\'>]+)["\']?`),
-	}
+	htmlTagLinkRegex    = regexp.MustCompile(`<\b[^>]*?\b((?i)href|(?i)src)\s*=\s*(\"([^"]*\")|'[^']*'|([^'">\s]+))`)
+	htmlTagLinkURLRegex = regexp.MustCompile(`((http|https|ftp|mailto):\/\/)?(\.?\/?[\w\.\-]+)+\/?([#?=&])?`)
```
Comment (swilen-iwanow) [inline pkg/hugo/processor.go:22]: hm I think those are not used.

File: pkg/markdown/html_links.go [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+var (
+	htmlTagLinkRegex    = regexp.MustCompile(`<\b[^>]*?\b((?i)href|(?i)src)\s*=\s*(\"([^"]*\")|'[^']*'|([^'">\s]+))`)
+	htmlTagLinkURLRegex = regexp.MustCompile(`((http|https|ftp|mailto):\/\/)?(\.?\/?[\w\.\-]+)+\/?([#?=&])?`)
+)
+
+// OnHTMLink is a callback function invoked on each link (src|href attribute)
+// found in HTML tag.
+// It is supplied a link destination and is expected to return destination,
+// that will update the link or error.
+type OnHTMLink func(destination []byte) ([]byte, error)
```
Comment (swilen-iwanow) [inline pkg/markdown/html_links.go:24]: I understand you stick to the convention used for the other links, but what do you think about using something like ProcessDestinationLinkFunc or Compute, in order to be self explanatory? It is not necessary to be done in this PR anyways.

File: pkg/markdown/html_links.go [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
```
Comment (swilen-iwanow) [inline pkg/markdown/html_links.go:25]: Missing doc for exported func UpdateHTMLLinkRefs

**Review by swilen-iwanow — APPROVED** [review]
only nits otherwise lgtm

File: pkg/markdown/html_links.go (hunk 2 above)
Comment (g-pavlov) [reply pkg/markdown/html_links.go]: Changed to reflect the intent better

File: pkg/markdown/html_links.go (hunk 3 above)
Comment (g-pavlov) [reply pkg/markdown/html_links.go:25]: added
